# Generated by Django 4.1 on 2022-08-30 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebook_link',
            new_name='telegram_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='twitter_link',
            new_name='vk_link',
        ),
    ]
