# Generated by Django 4.1 on 2022-08-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_facebook_link_team_telegram_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='destignation',
            new_name='designation',
        ),
    ]
