# Generated by Django 4.1 on 2022-08-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_destignation_team_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
