# Generated by Django 4.1 on 2022-08-31 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_firstname_team_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
